package eggervezoli.interfaz;


import eggervezoli.dominio.Restaurante;
import eggervezoli.dominio.Sistema;
import javax.swing.JPanel;

public class EvaluarRestaurante extends javax.swing.JPanel {

    private Sistema sistema;
    private JPanel contenedor;
    
    public EvaluarRestaurante(JPanel padre, Sistema sistema) {
        initComponents();
        this.sistema = sistema;
        this.contenedor = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        unaEstrella = new javax.swing.JCheckBox();
        dosEstrellas = new javax.swing.JCheckBox();
        tresEstrellas = new javax.swing.JCheckBox();
        cuatroEstrellas = new javax.swing.JCheckBox();
        cincoEstrellas = new javax.swing.JCheckBox();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        usuarioEvaluacion = new javax.swing.JTextField();
        comentariosEvaluacion = new javax.swing.JTextField();
        fechaEvaluacion = new javax.swing.JTextField();

        jLabel1.setText("Evaluar Restaurante");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Comentarios:");

        jLabel4.setText("Fecha:");

        jLabel5.setText("Calificación:");

        buttonGroup1.add(unaEstrella);
        unaEstrella.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        unaEstrella.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        unaEstrella.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        unaEstrella.setIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        unaEstrella.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled.png")); // NOI18N
        unaEstrella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unaEstrellaActionPerformed(evt);
            }
        });

        buttonGroup1.add(dosEstrellas);
        dosEstrellas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dosEstrellas.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        dosEstrellas.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        dosEstrellas.setIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        dosEstrellas.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled.png")); // NOI18N
        dosEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosEstrellasActionPerformed(evt);
            }
        });

        buttonGroup1.add(tresEstrellas);
        tresEstrellas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tresEstrellas.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        tresEstrellas.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        tresEstrellas.setIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        tresEstrellas.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled.png")); // NOI18N
        tresEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresEstrellasActionPerformed(evt);
            }
        });

        buttonGroup1.add(cuatroEstrellas);
        cuatroEstrellas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cuatroEstrellas.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        cuatroEstrellas.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        cuatroEstrellas.setIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        cuatroEstrellas.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled.png")); // NOI18N
        cuatroEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroEstrellasActionPerformed(evt);
            }
        });

        buttonGroup1.add(cincoEstrellas);
        cincoEstrellas.setDisabledIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        cincoEstrellas.setIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled22.png")); // NOI18N
        cincoEstrellas.setSelectedIcon(new javax.swing.ImageIcon("C:\\Users\\valen\\OneDrive\\Pictures\\ImagenesObligatorioIS\\Untitled.png")); // NOI18N

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");

        usuarioEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioEvaluacionActionPerformed(evt);
            }
        });

        fechaEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaEvaluacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comentariosEvaluacion)
                                    .addComponent(usuarioEvaluacion)
                                    .addComponent(fechaEvaluacion, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(unaEstrella)
                .addGap(18, 18, 18)
                .addComponent(dosEstrellas)
                .addGap(26, 26, 26)
                .addComponent(tresEstrellas)
                .addGap(29, 29, 29)
                .addComponent(cuatroEstrellas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(cincoEstrellas)
                .addGap(216, 216, 216))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addGap(18, 18, 18)
                .addComponent(guardar)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tresEstrellas)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(usuarioEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comentariosEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(fechaEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unaEstrella)
                            .addComponent(dosEstrellas)
                            .addComponent(cuatroEstrellas)
                            .addComponent(cincoEstrellas))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar)
                    .addComponent(cancelar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cuatroEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroEstrellasActionPerformed
        if(cincoEstrellas.isSelected()){
            cuatroEstrellas.getSelectedIcon();
                    
        }
    }//GEN-LAST:event_cuatroEstrellasActionPerformed

    private void unaEstrellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unaEstrellaActionPerformed
        if(dosEstrellas.isSelected()){
            unaEstrella.getSelectedIcon();
        }
    }//GEN-LAST:event_unaEstrellaActionPerformed

    private void dosEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosEstrellasActionPerformed
        if(tresEstrellas.isSelected()){
            dosEstrellas.getSelectedIcon();
                    
        }
    }//GEN-LAST:event_dosEstrellasActionPerformed

    private void tresEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresEstrellasActionPerformed
        if(cuatroEstrellas.isSelected()){
            tresEstrellas.getSelectedIcon();
        }
    }//GEN-LAST:event_tresEstrellasActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        Restaurante resto = sistema.getRestaurante();
        String usuario, comentario, fecha, calificacion;
        usuario = usuarioEvaluacion.getText();
        comentario = comentariosEvaluacion.getText();
        fecha = fechaEvaluacion.getText();
        calificacion = cantidadDeEstrellas();
        //Evaluacion evaluacion = new Evaluacion(calificacion, comentario, usuario, fecha);
        //si vamos a pedir solo usuario por nombre hay q crear metodo para buscar usuario
        //resto.addEvaluacion(evaluacion);
        
    }//GEN-LAST:event_guardarActionPerformed

    private void fechaEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaEvaluacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaEvaluacionActionPerformed

    private void usuarioEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioEvaluacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioEvaluacionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelar;
    private javax.swing.JCheckBox cincoEstrellas;
    private javax.swing.JTextField comentariosEvaluacion;
    private javax.swing.JCheckBox cuatroEstrellas;
    private javax.swing.JCheckBox dosEstrellas;
    private javax.swing.JTextField fechaEvaluacion;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JCheckBox tresEstrellas;
    private javax.swing.JCheckBox unaEstrella;
    private javax.swing.JTextField usuarioEvaluacion;
    // End of variables declaration//GEN-END:variables

    private String cantidadDeEstrellas() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
